language: python
jobs:
  include:
  - services: docker
    env:
    - BUILD_SOURCE_DISTRIBUTION="true"
env:
  global:
  - export TWINE_USERNAME=__token__
install:
- python -m pip install -U pip setuptools twine
script:
- |
  python setup.py install
  python setup.py sdist
  export UPLOAD_FILES=dist/*.tar.gz
after_success:
- python -m twine upload -p $TEST_TOKEN --repository-url https://test.pypi.org/legacy/ --skip-existing --verbose $UPLOAD_FILES;
- if [[ $TRAVIS_TAG ]]; then python -m twine upload -p $PYPI_TOKEN --skip-existing --verbose $UPLOAD_FILES; fi
